services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Incubator\WaveCart\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  TYPO3Incubator\WaveCart\Controller\Backend\OrderBackendController:
    public: true
