categories:
  WaveCart:
    label: 'Wave Cart'
  WaveCart.mail:
    label: 'Mail'
    parent: 'WaveCart'
  WaveCart.invoice:
    label: 'Invoice'
    parent: 'WaveCart'

settings:
  waveCart.invoice.company:
    label: 'Company'
    category: WaveCart.invoice
    description: 'Name of the Company for invoice generation'
    type: string
    default: 'Wave Cart'
  waveCart.cartPageId:
    label: 'Cart Page Id'
    category: WaveCart
    description: 'Pages id on which the shopping cart is located.'
    type: int
    default: 1
  waveCart.cartPid:
    label: 'Cart PID'
    category: WaveCart
    description: 'PID where the Cart Objects should be stored.'
    type: int
    default: 1
  waveCart.cartItemPid:
    label: 'Cart Items PID'
    category: WaveCart
    description: 'PID where the Cart Item Objects should be stored.'
    type: int
    default: 1
  waveCart.orderPid:
    label: 'Order PID'
    category: WaveCart
    description: 'PID where the Order Objects should be stored.'
    type: int
    default: 1
  waveCart.orderItemPid:
    label: 'Order Items PID'
    category: WaveCart
    description: 'PID where the Order Item Objects should be stored.'
    type: int
    default: 1
  waveCart.mailFromAddress:
    label: 'From E-Mail address'
    category: WaveCart.mail
    description: 'The E-Mail address that sends the mail. Usually a noreply'
    type: string
    default: 'noreply@wavecart.com'
  waveCart.mailFromSubject:
    label: 'Sender E-Mail subject'
    category: WaveCart.mail
    description: 'The E-Mail subject for the from E-mail.'
    type: string
    default: 'Your order at WaveCart'
  waveCart.mailReceiverAddress:
    label: 'Receiver E-Mail address'
    category: WaveCart.mail
    description: 'The E-Mail address for the receiver mail.'
    type: string
    default: 'shop@wavecart.com'
  waveCart.mailReceiverSubject:
    label: 'Receiver E-Mail subject'
    category: WaveCart.mail
    description: 'The E-Mail subject for the receiver E-mail.'
    type: string
    default: 'New order at WaveCart'
